
threaded_cx_count_greedy3:
	g++ greedy3.cpp greedy.cpp simulator.cpp sp3.cpp pattern.cpp state_tracker.cpp threaded_cx_count_greedy3.cpp -std=c++11 -O3

threaded_cx_count_search:
	g++ search.cpp vqc.cpp simulator.cpp threaded_cx_count_search.cpp -std=c++11 -O3

threaded_cx_count_aa:
	g++ threaded_cx_vs_fidelity_aa.cpp simulator.cpp vqc.cpp -std=c++11 -O3
cx_count_greedy3:
	g++ greedy3.cpp greedy.cpp simulator.cpp sp3.cpp pattern.cpp state_tracker.cpp cx_count_greedy3.cpp -std=c++11 -O3

cx_count_search:
	g++ search.cpp vqc.cpp simulator.cpp cx_count_search.cpp -std=c++11 -O3

timer_greedy3:
	g++ timer_greedy3.cpp greedy3.cpp greedy.cpp simulator.cpp sp3.cpp pattern.cpp state_tracker.cpp -std=c++11 -O3

timer_search:
	g++ search.cpp timer_search.cpp simulator.cpp vqc.cpp -std=c++11 -O3

timer_aa:
	g++ timer_aa.cpp vqc.cpp simulator.cpp -std=c++11 -O3
